- name: Upgrade all packages
  apt: 
    name: "*"
    state: latest

- name: Update all packages
  apt:
    upgrade: dist

- name: Install common packages
  apt:
    pkg: "{{ packages }}"
    state: present

- name: Change Hostname
  hostname:
    name: "{{ new_hostname }}"

- name: copy .bashrc for "{{ ansible_user }}"
  copy:
    src: "{{ item }}"
    dest: "~"
    owner: root
    group: root
    mode: 0644
  with_items:
    - .bashrc  